48 rename entries to notes
mitwelten/mitwelten-db-backend pull request #49
Opened 2023-09-18 20:54 UTC by cspindler

2023-09-18 21:03 UTC, cspindler commented
For testing: notes, tags and crossrefs can be copied to `dev` schema using `schema/migrations/migrate_v2_3__v2_4_dev.py`. Don't forget to truncate the tables before:

```sql
truncate dev.mm_tags_notes restart identity cascade;
truncate dev.tags restart identity cascade;
truncate dev.notes restart identity cascade;
truncate dev.files_note restart identity cascade;
```

---

Changes to the entries router are visible in all commits to `entries.py` except the file-renaming commit 9dfb1d18ec513bbf187a4d23c3ca9facf9f7359a

2023-09-19 20:09 UTC, cspindler reviewed
Check if PR #50 can be implemented to remove/consolidate the remaining viz endpoints

2023-09-19 20:11 UTC, cspindler commented on services/api/routers/tags.py
Check if PR https://github.com/mitwelten/mitwelten-db-backend/pull/50 can be implemented to remove/consolidate the remaining viz endpoints

2023-09-20 13:23 UTC, cspindler reviewed
Checked through, found all requirements to be met

2023-09-20 13:23 UTC, cspindler commented on services/api/routers/notes.py
- Add user_id to user_sub field on PUT(insert only)
- Resolve user_id to full name on GET

2023-09-20 13:23 UTC, cspindler commented on services/api/routers/notes.py
> +@router.get('/notes', response_model=List[Note], response_model_exclude_none=True)
Check if authenticated, and filter according to `public` attribute

2023-09-20 13:23 UTC, cspindler commented on services/api/routers/tags.py
Was implemented

2023-09-20 13:23 UTC, cspindler commented on services/api/routers/notes.py
Also public flag  is added to the model and can now be set on insert / patch. Only users with 'internal' role can create public notes, others always create non-public notes.

2023-09-21 09:22 UTC, AndriWild requested changes

2023-09-21 09:22 UTC, AndriWild commented on services/api/routers/notes.py
> +        e['files'] = [{'name': f['file_name'], 'link': f['object_name'], 'type': f['file_type']} for f in f_l if f['file_id'] != None]
Change `'link'` to `'object_name'`

2023-09-21 09:22 UTC, AndriWild commented on services/api/routers/notes.py
> +        if body.id:
Change `body.id` to `body.tag_id`

2023-09-21 09:22 UTC, AndriWild commented on services/api/routers/notes.py
> +    if body.id:
Change `body.id` to `body.tag_id`

2023-09-21 09:22 UTC, AndriWild commented on services/api/routers/notes.py
> +    Deletes a tag from an note
Typo: an note → a note

2023-09-21 09:22 UTC, AndriWild commented on services/api/routers/notes.py
> +    ## Deletes an note
Typo: an note → a note

2023-09-21 09:22 UTC, AndriWild commented on services/api/routers/notes.py
> +    ## Updates an note
Typo: an note → a note

2023-09-21 09:22 UTC, AndriWild commented on services/api/routers/notes.py
> +    Adds a tag for an note
Typo: an note → a note

2023-09-21 09:22 UTC, AndriWild commented on services/api/routers/notes.py
> +    Adds a file for an note
Typo: an note → a note

2023-09-21 09:22 UTC, AndriWild commented on services/api/routers/minio.py
> +@router.post('/files/discover/', dependencies=[Depends(AuthenticationChecker(['internal']))])
Remove `/` at the end of the path

2023-09-21 13:44 UTC, merged